### ISSUE TITLE
Barrel Files

### ISSUE THREAD

**Issue by MohitS69** [oxc-project/oxc-jest#17]
In our project we are heavily relying on Barrel Files (typical index.ts files to export). Is there any way to run my test cases without stumbling into circular dependencies. Jest doesn't support tree shaking and that's why when you import something from a index.ts file it will try to  import whole module and in this way you end up stumbling into circular dependency error.
I don't know this package supports or not.

**Comment by Boshen** [comment]
`oxc-jest` is not currently being developed, so we cannot answer your question right now.
